use PRICINGDB;

INSERT INTO filtroCuentas
(tipo, descripcion)
VALUES
(1, 'AHORRO JUVENIL COOMEVITA PN'),
(9, 'CUENTAS DE AHORROS AFC'),
(16, 'CARTERA COLECTIVA'),
(21, 'CUENTA DE AHORROS FONDO DE LIQUIDEZ'),
(54, 'CUENTA PAP TRADICIONAL'),
(55, 'CUENTA PAP EMPRESARIAL'),
(56, 'CUENTA PAP EDUCATIVO'),
(57, 'CUENTA PAP ASOCIADO'),
(58, 'CUENTA PAP VIVIENDA');
