INSERT INTO homologaSector
(codeCobis,sectorCobis, code)
values
('A', 'AGRICULTURA, GANADERÍA, CAZA, SILVICULTURA Y PESCA', 4),
('B', 'EXPLOTACIÓN DE MINAS Y CANTERAS', 4),
('C', 'INDUSTRIAS MANUFACTURERAS', 26),
('F', 'CONSTRUCCIÓN', 9),
('G', 'COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AU', 31),
('H', 'TRANSPORTE Y ALMACENAMIENTO', 16),
('I', 'ALOJAMIENTO Y SERVICIOS DE COMIDA', 4),
('J', 'INFORMACIÓN Y COMUNICACIONES', 4),
('K', 'ACTIVIDADES FINANCIERAS Y DE SEGUROS', 17),
('O', 'ADMINISTRACIÓN PÚBLICA Y DEFENSA; PLANES DE SEGURIDAD SOCIAL DE', 7),
('P', 'EDUCACIÓN', 24),
('Q', 'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA', 4),
('R', 'ACTIVIDADES ARTÍSTICAS, DE ENTRETENIMIENTO Y RECREACIÓN', 4),
('S', 'OTRAS ACTIVIDADES DE SERVICIOS', 4),
('T', 'ACTIVIDADES DE LOS HOGARES INDIVIDUALES EN CALIDAD DE EMPLEADORE', 4),
('U', 'ACTIVIDADES DE ORGANIZACIONES Y ENTIDADES EXTRATERRITORIALES', 7),
('V', 'OTRAS CLASIFICACIONES', 4);