apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banca
  name: pricing-24052021
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pricing
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pricing
    spec:
      containers:
      - image: 618817091491.dkr.ecr.us-east-1.amazonaws.com/apppreferenciales:1.0.30C
        name: pricing
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER_MYSQL #DB
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: usuario_aurora
        - name: DB_PASS_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: password_aurora
        - name: DB_HOST_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_aurora
        - name: DB_NAME_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: nombre_bd_aurora
        - name: DB_PORT_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_bd_aurora
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_despliegue
        - name: SQUEMA_AURORA
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: squema_aurora
        - name: KEY_SECRET #AUTH APP
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_app
        - name: AUT_COGNITO_USU #AUTH SERVICIOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_cognito_usu
        - name: AUT_COGNITO_PASS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_cognito_pass
        - name: AUT_KNIME_USE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_knime_usu
        - name: AUT_KNIME_PASS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_knime_pass
        - name: MAIL_HOST #EMAIL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_mail
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_mail
        - name: MAIL_SECURE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: ssl_tls_mail
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: usuario_mail
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: password_mail
        - name: MAIL_FROM
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: from_main
        - name: URL_APP #URL APP
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_aplicacion
        - name: URL_DOCUMENTOS #URL DOCUMENTOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_documentos
        - name: URL_HOST_KNIME #URL SERVICIOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_knime
        - name: URL_PORT_KNIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_knime
        - name: URL_PATH_KNIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_knime
        - name: URL_HOST_COGNITO
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_cognito
        - name: URL_PATH_COGNITO
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_cognito
        - name: URL_HOST_CLIENTEPJ
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_clientepj
        - name: URL_PORT_CLIENTEPJ
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_clientepj
        - name: URL_PATH_CLIENTEPJ
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_clientepj
        - name: URL_HOST_CLIENTEPN
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_clientepn
        - name: URL_PORT_CLIENTEPN
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_clientepn
        - name: URL_PATH_CLIENTEPN
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_clientepn
        - name: URL_HOST_PROFILE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_profile
        - name: URL_PORT_PROFILE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_profile
        - name: URL_PATH_PROFILE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_profile
        - name: URL_HOST_SOAP_CHANNELADAPTER
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_adaptador
        - name: URL_PORT_SOAP_CHANNELADAPTER
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_adaptador
        - name: URL_PATH_SOAP_CHANNELADAPTER
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_adaptador
        - name: URL_HOST_SOAP_USOGENERAL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_usogeneral
        - name: URL_PORT_SOAP_USOGENERAL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_usogeneral
        - name: URL_PATH_SOAP_USOGENERAL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_usogeneral
        - name: TIMEDOUT_lOGIN #TIMEDOUT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: timedout_sesiones
        - name: TIMEDOUT_SERVICES
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: timedout_servicios
        - name: TIMEDOUT_KNIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: timedout_knime
        - name: NEXT_PUBLIC_INACTIVITY_TIME #SESSION INACTIVITY
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: inactivity_time
        - name: NEXT_PUBLIC_MODAL_DISPLAY_TIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: modal_display_time
        - name: NEXT_PUBLIC_SESSION_EXPIRATION_TIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: session_expiration_time
        - name: AWS_S3_REGION #BUCKET_S3
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: region_aws
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: nombre_bucket
        - name: AWS_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: access_key_bucket
        - name: AWS_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: secret_access_bucket
        - name: AWS_S3_PATH
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_bucket      
        - name: SERV_SOAP_USERNAME #USERNAME SERVICES
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: servi_soap_username
        - name: USOGENERAL_USERNAME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: usogeneral_username
        - name: SERV_SOAP_USERTOKEN
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: servi_soap_usertoken
        - name: USOGENERAL_USERTOKEN
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: usogeneral_usertoken      
        - name: SERVICIO_CORE
          value: "pricing"
        - name: SERVICIO_MEDIACION
          value: "pricing"
        - name: NIVEL_LOG
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  namespace: banca
  name: pricing-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:618817091491:certificate/bdc470c9-e382-4f6a-9419-66f5efa73d64"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pricing
