apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: banca
  name: pricing-24052021
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pricing
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pricing
    spec:
      containers:
      - image: 618817091491.dkr.ecr.us-east-1.amazonaws.com/apppreferenciales:1.0.32
        name: pricing
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER_MYSQL #DB
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: usuario_aurora
        - name: DB_PASS_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: password_aurora
        - name: DB_HOST_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_aurora
        - name: DB_NAME_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: nombre_bd_aurora
        - name: DB_PORT_MYSQL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_bd_aurora
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_despliegue
        - name: SQUEMA_AURORA
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: squema_aurora
        - name: KEY_SECRET #AUTH APP
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_app
        - name: AUT_COGNITO_USU #AUTH SERVICIOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_cognito_usu
        - name: AUT_COGNITO_PASS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_cognito_pass
        - name: AUT_KNIME_USE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_knime_usu
        - name: AUT_KNIME_PASS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: auth_knime_pass
        - name: MAIL_HOST #EMAIL
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_mail
        - name: MAIL_PORT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_mail
        - name: MAIL_SECURE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: ssl_tls_mail
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: usuario_mail
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: password_mail
        - name: MAIL_FROM
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: from_main
        - name: URL_APP #URL APP
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_aplicacion
        - name: URL_DOCUMENTOS #URL DOCUMENTOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_documentos
        - name: URL_HOST_KNIME #URL SERVICIOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_knime
        - name: URL_PORT_KNIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_knime
        - name: URL_PATH_KNIME
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_knime
        - name: URL_HOST_COGNITO
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_cognito
        - name: URL_PATH_COGNITO
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_cognito
        - name: URL_HOST_PROFILE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: url_profile
        - name: URL_PORT_PROFILE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: puerto_profile
        - name: URL_PATH_PROFILE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_profile
        - name: TIMEDOUT_lOGIN #TIMEDOUT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: timedout_sesiones
        - name: TIMEDOUT_SERVICES #TIMEDOUT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: timedout_servicios
        - name: TIMEDOUT_KNIME #TIMEDOUT
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: timedout_knime
        - name: NEXT_PUBLIC_INACTIVITY_TIME #SESSION INACTIVITY
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: inactivity_time
        - name: NEXT_PUBLIC_MODAL_DISPLAY_TIME #SESSION INACTIVITY
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: modal_display_time
        - name: NEXT_PUBLIC_SESSION_EXPIRATION_TIME #SESSION INACTIVITY
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: session_expiration_time
        - name: AWS_S3_REGION #BUCKET_S3
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: region_aws
        - name: AWS_S3_BUCKET_NAME #BUCKET_S3
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: nombre_bucket
        - name: AWS_S3_ACCESS_KEY_ID #BUCKET_S3
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: access_key_bucket
        - name: AWS_S3_SECRET_ACCESS_KEY #BUCKET_S3
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: secret_access_bucket
        - name: AWS_S3_PATH #BUCKET_S3
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: path_bucket
        - name: KEYCLOAK_GRANT_TYPE #AUTH KEYCLOAK 
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: keycloak_auth_type
        - name: KEYCLOAK_CLIENT_ID #AUTH KEYCLOAK 
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: keycloak_auth_id
        - name: KEYCLOAK_CLIENT_SECRET #AUTH KEYCLOAK 
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: keycloak_auth_secret
        - name: KEYCLOAK_TOKEN_HOST #URL KEYCLOAK
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: keycloak_host
        - name: KEYCLOAK_TOKEN_PORT #URL KEYCLOAK 
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: keycloak_port
        - name: KEYCLOAK_TOKEN_PATH #URL KEYCLOAK
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: keycloak_path
        - name: URL_HOST_CONSULTA_UNICA_DATOS_CLIENTE #URL CONSULTA_UNICA_DATOS_CLIENTE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: consulta_unica_cliente_host
        - name: URL_PORT_CONSULTA_UNICA_DATOS_CLIENTE #URL CONSULTA_UNICA_DATOS_CLIENTE 
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: consulta_unica_cliente_port
        - name: URL_PATH_CONSULTA_UNICA_DATOS_CLIENTE #URL CONSULTA_UNICA_DATOS_CLIENTE
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: consulta_unica_cliente_path
        - name: URL_HOST_CUENTA_SOBREGIRO #URL CONSULTAR CUENTAS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: cuenta_sobregiro_host
        - name: URL_PORT_CUENTA_SOBREGIRO #URL CONSULTAR CUENTAS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: cuenta_sobregiro_port
        - name: URL_PATH_CUENTA_SOBREGIRO #URL CONSULTAR CUENTAS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: cuenta_sobregiro_path
        - name: URL_HOST_CATALOGO #URL CATALOGOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: catalogo_host
        - name: URL_PORT_CATALOGO #URL CATALOGOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: catalogo_port
        - name: URL_PATH_CATALOGO #URL CATALOGOS
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: catalogo_path
        - name: URL_HOST_OFICINA_HOMOLOGADA #URL OFICINA HOMOLOGADA
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: oficinaHomologada_host
        - name: URL_PORT_OFICINA_HOMOLOGADA #URL OFICINA HOMOLOGADA
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: oficinaHomologada_port
        - name: URL_PATH_OFICINA_HOMOLOGADA #URL OFICINA HOMOLOGADA
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: oficinaHomologada_path
        - name: CATALOGO_HOMOLOGADO #CATALOGO HOMOLOGADO
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: catalogoHomologado_path
        - name: ORINATINGBANK #header
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: header_orinatingbanck
        - name: CALLBACKURL #header
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: header_callbackurl
        - name: CHANNEL #header
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: header_channel
        - name: PRIORITY #metadata
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: metadata_priority
        - name: SERVICELEVELAGREEMENT #metadata
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: metadata_servicelevel
        - name: PROCESSINGMODE #metadata
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: metadata_processingmode
        - name: APPNAME #clientApp
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: clientapp_appname
        - name: APPVERSION #clientApp
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: clientapp_appversion
        - name: NODE_TLS_REJECT_UNAUTHORIZED #Activar desactivar certificados
          valueFrom:
            secretKeyRef:
              name: pricing-db-secret
              key: tls_unauthorized
        - name: SERVICIO_CORE
          value: "pricing"
        - name: SERVICIO_MEDIACION
          value: "pricing"
        - name: NIVEL_LOG
          value: "3"
        - name: TZ
          value: America/Bogota
---
apiVersion: v1
kind: Service
metadata:
  namespace: banca
  name: pricing-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:618817091491:certificate/bdc470c9-e382-4f6a-9419-66f5efa73d64"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pricing
