-- stored procedure insert usuarios v1
DELIMITER $$
	CREATE PROCEDURE insertUsuario (IN nwUSU VARCHAR(45), NOM VARCHAR(80), COR VARCHAR(80), CAR INT, OFI INT, REG INT, CAN INT, EDO INT, OBN VARCHAR(200), USU VARCHAR(15))
		BEGIN
			INSERT INTO usuario ( USUARIO, NOMBRE, CORREO, COD_CARGO, COD_OFICINA, COD_REGIONAL, COD_CANAL, ESTADO_USU, OBSERVACION, codUsu)
			VALUES(nwUSU, NOM, COR, CAR, OFI, REG, CAN, EDO, OBN, USU);
		END$$
DELIMITER ;

DROP PROCEDURE insertUsuario;
CALL insertUsuario('usu1040', 'PRUEBAS USER', 'PRUEBAS@CORREO.COM', 1, 1801, 2, 2, 1, 'INICIAL');