DELIMITER $$
	CREATE PROCEDURE updateEstadoUsuario (IN pUSU VARCHAR(45), EDO INT, OBN VARCHAR(200), USU VARCHAR(15))
		BEGIN
			UPDATE usuario AS U 
			SET U.ESTADO_USU = EDO, U.OBSERVACION = OBN, U.codUsu = USU
			WHERE U.USUARIO = pUSU;
		END$$
DELIMITER ;
DROP PROCEDURE updateEstadoUsuario;
CALL updateEstadoUsuario('AMZR5511', 3, 'PRUEBAS ELIMINACION', 'MAPO1982')