DELIMITER $$
	CREATE PROCEDURE updateUsuario (IN pUSU VARCHAR(45), CAR INT, OFI INT, REG INT, CAN INT, EDO INT, OBN VARCHAR(200), USU VARCHAR(15))
		BEGIN
			UPDATE usuario AS U 
			SET U.COD_CARGO = CAR, U.COD_OFICINA = OFI, U.COD_REGIONAL = REG, U.COD_CANAL = CAN,
			U.ESTADO_USU = EDO, U.OBSERVACION = OBN, U.codUsu =  USU
			WHERE U.USUARIO = pUSU;
		END$$
DELIMITER ;

DROP PROCEDURE updateUsuario;
CALL updateUsuario('usu1040', 2, 1802, 2, 2, 2, 'cambios', 'mapo1982');