DELIMITER $$
DROP TRIGGER IF EXISTS tr_actualizar_usuarios;
CREATE TRIGGER tr_actualizar_usuarios
AFTER UPDATE ON usuario
FOR EACH ROW
BEGIN
  IF NOT OLD.COD_OFICINA <=> NEW.COD_OFICINA THEN
    INSERT INTO log_pricing 
    (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES 
    (NEW.codUsu, '3', 'UPDATE USUARIO', OLD.USUARIO, 'COD_OFICINA', NOW(), OLD.COD_OFICINA, NEW.COD_OFICINA, NULL);
  END IF;

  IF NOT OLD.COD_CANAL <=> NEW.COD_CANAL THEN
    INSERT INTO log_pricing 
    (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES 
    (NEW.codUsu, '3', 'UPDATE USUARIO', OLD.USUARIO, 'COD_CANAL', NOW(), OLD.COD_CANAL, NEW.COD_CANAL, NULL);
  END IF;

  IF NOT OLD.COD_REGIONAL <=> NEW.COD_REGIONAL THEN
    INSERT INTO log_pricing 
    (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES 
    (NEW.codUsu, '3', 'UPDATE USUARIO', OLD.USUARIO, 'COD_REGIONAL', NOW(), OLD.COD_REGIONAL, NEW.COD_REGIONAL, NULL);
  END IF;

  IF NOT OLD.COD_CARGO <=> NEW.COD_CARGO THEN
    INSERT INTO log_pricing 
    (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES 
    (NEW.codUsu, '3', 'UPDATE USUARIO', OLD.USUARIO, 'COD_CARGO', NOW(), OLD.COD_CARGO, NEW.COD_CARGO, NULL);
  END IF;

  IF NOT OLD.ESTADO_USU <=> NEW.ESTADO_USU THEN
    INSERT INTO log_pricing 
    (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES 
    (NEW.codUsu, 
    CASE
      WHEN NEW.ESTADO_USU = '1' THEN '1'
      WHEN NEW.ESTADO_USU = '2' THEN '2'
      WHEN NEW.ESTADO_USU = '0' THEN '0'
      ELSE '3'
    END,
    'UPDATE ESTADO', 
    OLD.USUARIO, 'ESTADO_USU', NOW(), OLD.ESTADO_USU, NEW.ESTADO_USU, NEW.OBSERVACION);
  END IF;
END$$
DELIMITER ;