DELIMITER $$
DROP TRIGGER IF EXISTS tr_insert_usuarios;
CREATE TRIGGER tr_insert_usuarios
AFTER INSERT ON usuario
FOR EACH ROW
BEGIN
  INSERT INTO log_pricing 
  (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
  VALUES
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'NOMBRE', NOW(), NULL, NEW.NOMBRE, NULL),
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'USUARIO', NOW(), NULL, NEW.USUARIO, NEW.OBSERVACION),
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'CORREO', NOW(), NULL, NEW.CORREO, NULL),
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'COD_OFICINA', NOW(), NULL, NEW.COD_OFICINA, NULL),
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'COD_CANAL', NOW(), NULL, NEW.COD_CANAL, NULL),
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'COD_REGIONAL', NOW(), NULL, NEW.COD_REGIONAL, NULL),
  (NEW.codUsu, '1', 'INSERT USUARIO', NULL, 'COD_CARGO', NOW(), NULL, NEW.COD_CARGO, NULL);
END$$
DELIMITER ;