DELIMITER $$
  DROP TRIGGER IF EXISTS tr_update_perfil;
  CREATE TRIGGER tr_update_perfil
  AFTER DELETE ON perfiles_usuario
  FOR EACH ROW
  BEGIN
    INSERT INTO log_pricing 
    (ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES
    ('3', 'DELETE PERFIL', OLD.USUARIO, 'COD_PERFIL', NOW(), OLD.COD_PERFIL, NULL, 'Perfil Anterior');
  END$$
DELIMITER ;