DELIMITER $$
  DROP TRIGGER IF EXISTS tr_insert_perfil;
  CREATE TRIGGER tr_insert_perfil
  AFTER INSERT ON perfiles_usuario
  FOR EACH ROW
  BEGIN
    INSERT INTO log_pricing 
    (USUARIO, ACCION, EVENTO, REGISTRO_MODIFICADO, CAMPO_MODIFICADO, FECHA, DATA_ACTUAL, DATA_NUEVA, OBSERVACION)
    VALUES
    (NEW.codUsu, '1', 'INSERT PERFIL', NEW.USUARIO, 'COD_PERFIL', NOW(), NULL, NEW.COD_PERFIL, 'Perfil Nuevo');
  END$$
DELIMITER ;